import {defineField, defineType} from 'sanity'

export default defineType({
    name: 'groupBlock',
    title: 'Group',
    type: 'object',
    fields: [
      defineField({name: 'title', title: 'Title', type: 'string',}),
      
      defineField({
        name: 'blocks',
        title: 'Blocks',
        type: 'array',
        of: [
          {type: 'textBlock'},
          {type: 'imageBlock'},
        ],
      }),
  
      defineField({name: 'link', title: 'Link', type: 'url'}),
      defineField({name: 'openInNewTab', title: 'Open in new tab', type: 'boolean', initialValue: false}),
      defineField({name: 'shareLayoutSettings', title: 'Share layout settings across devices', type: 'boolean', initialValue: true}),
      defineField({
        name: 'contentDirection',
        title: 'Content direction',
        type: 'string',
        initialValue: 'column',
        options: {list: [
          {title: 'Vertical', value: 'column'},
          {title: 'Horizontal', value: 'row'},
        ]},
      }),
      defineField({
        name: 'verticalOnMobile',
        title: 'Vertical on mobile',
        type: 'boolean',
        initialValue: true,
        hidden: ({parent}) => parent?.contentDirection !== 'row',
      }),
      defineField({
        name: 'horizontalAlignment',
        title: 'Horizontal alignment',
        type: 'string',
        initialValue: 'flex-start',
        options: {list: [
          {title: 'Left', value: 'flex-start'},
          {title: 'Center', value: 'center'},
          {title: 'Right', value: 'flex-end'},
          {title: 'Space between', value: 'space-between'},
        ]},
        hidden: ({parent}) => parent?.contentDirection !== 'row',
      }),
      defineField({
        name: 'horizontalAlignmentMobile',
        title: 'Horizontal alignment (Mobile)',
        type: 'string',
        options: {list: [
          {title: 'Left', value: 'flex-start'},
          {title: 'Center', value: 'center'},
          {title: 'Right', value: 'flex-end'},
          {title: 'Space between', value: 'space-between'},
        ]},
        hidden: ({parent}) => parent?.contentDirection !== 'row' || !!parent?.shareLayoutSettings,
      }),
      defineField({
        name: 'verticalAlignment',
        title: 'Vertical alignment',
        type: 'string',
        initialValue: 'center',
        options: {list: [
          {title: 'Top', value: 'flex-start'},
          {title: 'Center', value: 'center'},
          {title: 'Bottom', value: 'flex-end'},
        ]},
        hidden: ({parent}) => parent?.contentDirection !== 'row',
      }),
      defineField({
        name: 'verticalAlignmentMobile',
        title: 'Vertical alignment (Mobile)',
        type: 'string',
        options: {list: [
          {title: 'Top', value: 'flex-start'},
          {title: 'Center', value: 'center'},
          {title: 'Bottom', value: 'flex-end'},
        ]},
        hidden: ({parent}) => parent?.contentDirection !== 'row' || !!parent?.shareLayoutSettings,
      }),
      defineField({
        name: 'alignBaseline',
        title: 'Align baseline',
        type: 'boolean',
        initialValue: false,
        hidden: ({parent}) => parent?.verticalAlignment !== 'flex-end',
      }),
      defineField({
        name: 'horizontalAlignmentColumn',
        title: 'Horizontal alignment (column)',
        type: 'string',
        initialValue: 'flex-start',
        options: {list: [
          {title: 'Left', value: 'flex-start'},
          {title: 'Center', value: 'center'},
          {title: 'Right', value: 'flex-end'},
        ]},
        hidden: ({parent}) => parent?.contentDirection === 'row',
      }),
      defineField({
        name: 'horizontalAlignmentColumnMobile',
        title: 'Horizontal alignment (column, Mobile)',
        type: 'string',
        options: {list: [
          {title: 'Left', value: 'flex-start'},
          {title: 'Center', value: 'center'},
          {title: 'Right', value: 'flex-end'},
        ]},
        hidden: ({parent}) => parent?.contentDirection === 'row' || !!parent?.shareLayoutSettings,
      }),
      defineField({
        name: 'verticalAlignmentColumn',
        title: 'Vertical alignment (column)',
        type: 'string',
        initialValue: 'center',
        options: {list: [
          {title: 'Top', value: 'flex-start'},
          {title: 'Center', value: 'center'},
          {title: 'Bottom', value: 'flex-end'},
          {title: 'Space between', value: 'space-between'},
        ]},
        hidden: ({parent}) => parent?.contentDirection !== 'column',
      }),
      defineField({
        name: 'verticalAlignmentColumnMobile',
        title: 'Vertical alignment (column, Mobile)',
        type: 'string',
        options: {list: [
          {title: 'Top', value: 'flex-start'},
          {title: 'Center', value: 'center'},
          {title: 'Bottom', value: 'flex-end'},
          {title: 'Space between', value: 'space-between'},
        ]},
        hidden: ({parent}) => parent?.contentDirection !== 'column' || !!parent?.shareLayoutSettings,
      }),
      defineField({
        name: 'gap',
        title: 'Gap',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 12,
      }),
      defineField({
        name: 'gapMobile',
        title: 'Gap (Mobile)',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        hidden: ({parent}) => !!parent?.shareLayoutSettings,
      }),
  
      defineField({
        name: 'width',
        title: 'Width',
        type: 'string',
        initialValue: 'fill',
        options: {list: [
          {title: 'Fit content', value: 'fit-content'},
          {title: 'Fill', value: 'fill'},
          {title: 'Custom', value: 'custom'},
        ]},
      }),
      defineField({
        name: 'customWidth',
        title: 'Custom width (%)',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 100,
        hidden: ({parent}) => parent?.width !== 'custom',
      }),
      defineField({
        name: 'widthMobile',
        title: 'Width (Mobile)',
        type: 'string',
        initialValue: 'fill',
        options: {list: [
          {title: 'Fit content', value: 'fit-content'},
          {title: 'Fill', value: 'fill'},
          {title: 'Custom', value: 'custom'},
        ]},
      }),
      defineField({
        name: 'customWidthMobile',
        title: 'Custom width (Mobile, %)',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 100,
        hidden: ({parent}) => parent?.widthMobile !== 'custom',
      }),
      defineField({
        name: 'height',
        title: 'Height',
        type: 'string',
        initialValue: 'fit',
        options: {list: [
          {title: 'Fit content', value: 'fit'},
          {title: 'Fill', value: 'fill'},
          {title: 'Custom', value: 'custom'},
        ]},
      }),
      defineField({
        name: 'customHeight',
        title: 'Custom height (%)',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 100,
        hidden: ({parent}) => parent?.height !== 'custom',
      }),
  
      defineField({name: 'shareAppearanceSettings', title: 'Share appearance settings across devices', type: 'boolean', initialValue: true}),
      defineField({
        name: 'inheritColorScheme',
        title: 'Inherit color scheme',
        type: 'boolean',
        initialValue: true,
      }),
      defineField({
        name: 'colorScheme',
        title: 'Color scheme',
        type: 'string',
        initialValue: 'scheme-1',
        options: {list: [
          {title: 'Scheme 1', value: 'scheme-1'},
          {title: 'Scheme 2', value: 'scheme-2'},
          {title: 'Scheme 3', value: 'scheme-3'},
          {title: 'Scheme 4', value: 'scheme-4'},
          {title: 'Scheme 5', value: 'scheme-5'},
        ]},
        hidden: ({parent}) => !!parent?.inheritColorScheme,
      }),
      defineField({
        name: 'backgroundMedia',
        title: 'Background media',
        type: 'string',
        initialValue: 'none',
        options: {list: [
          {title: 'None', value: 'none'},
          {title: 'Image', value: 'image'},
          {title: 'Video', value: 'video'},
        ]},
      }),
      defineField({
        name: 'backgroundMediaMobile',
        title: 'Background media (Mobile)',
        type: 'string',
        initialValue: 'none',
        options: {list: [
          {title: 'None', value: 'none'},
          {title: 'Image', value: 'image'},
          {title: 'Video', value: 'video'},
        ]},
        hidden: ({parent}) => !!parent?.shareAppearanceSettings,
      }),
      defineField({
        name: 'video',
        title: 'Video',
        type: 'file',
        hidden: ({parent}) => parent?.backgroundMedia !== 'video',
      }),
      defineField({
        name: 'videoPosition',
        title: 'Video position',
        type: 'string',
        initialValue: 'cover',
        options: {list: [
          {title: 'Cover', value: 'cover'},
          {title: 'Contain', value: 'contain'},
        ]},
        hidden: ({parent}) => parent?.backgroundMedia !== 'video',
      }),
      defineField({
        name: 'backgroundImage',
        title: 'Background image',
        type: 'image',
        hidden: ({parent}) => parent?.backgroundMedia !== 'image',
      }),
      defineField({
        name: 'backgroundImagePosition',
        title: 'Image position',
        type: 'string',
        initialValue: 'cover',
        options: {list: [
          {title: 'Cover', value: 'cover'},
          {title: 'Fit', value: 'fit'},
        ]},
        hidden: ({parent}) => parent?.backgroundMedia !== 'image',
      }),
  
      defineField({
        name: 'border',
        title: 'Borders',
        type: 'string',
        initialValue: 'none',
        options: {list: [
          {title: 'None', value: 'none'},
          {title: 'Solid', value: 'solid'},
        ]},
      }),
      defineField({
        name: 'borderWidth',
        title: 'Border width (px)',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 10, step: 0.5},
        initialValue: 1,
        hidden: ({parent}) => parent?.border === 'none',
      }),
      defineField({
        name: 'borderOpacity',
        title: 'Border opacity (%)',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 100,
        hidden: ({parent}) => parent?.border === 'none',
      }),
      defineField({
        name: 'borderRadius',
        title: 'Border radius (px)',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 0,
      }),
      defineField({
        name: 'borderRadiusMobile',
        title: 'Border radius (Mobile, px)',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 0,
        hidden: ({parent}) => !!parent?.shareAppearanceSettings,
      }),
  
      defineField({name: 'visibility', title: 'Visibility', type: 'string', initialValue: 'visible-all', options: {list: [
        {title: 'All devices', value: 'visible-all'},
        {title: 'Mobile only', value: 'hidden--desktop'},
        {title: 'Desktop only', value: 'hidden--mobile'},
      ]}}),
  
      defineField({name: 'toggleOverlay', title: 'Background overlay', type: 'boolean', initialValue: false}),
      defineField({name: 'overlayColor', title: 'Overlay color', type: 'color', hidden: ({parent}) => !parent?.toggleOverlay}),
      defineField({
        name: 'overlayStyle',
        title: 'Overlay style',
        type: 'string',
        initialValue: 'solid',
        options: {list: [
          {title: 'Solid', value: 'solid'},
          {title: 'Gradient', value: 'gradient'},
        ]},
        hidden: ({parent}) => !parent?.toggleOverlay,
      }),
      defineField({
        name: 'gradientDirection',
        title: 'Gradient direction',
        type: 'string',
        initialValue: 'to top',
        options: {list: [
          {title: 'Up', value: 'to top'},
          {title: 'Down', value: 'to bottom'},
        ]},
        hidden: ({parent}) => !parent?.toggleOverlay || parent?.overlayStyle !== 'gradient',
      }),
  
      defineField({name: 'sharePaddingSettings', title: 'Share padding settings across devices', type: 'boolean', initialValue: true}),
      defineField({name: 'paddingBlockStart', title: 'Padding top', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, initialValue: 0}),
      defineField({name: 'paddingBlockStartMobile', title: 'Top (Mobile)', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, hidden: ({parent}) => !!parent?.sharePaddingSettings, initialValue: 0}),
      defineField({name: 'paddingBlockEnd', title: 'Padding bottom', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, initialValue: 0}),
      defineField({name: 'paddingBlockEndMobile', title: 'Bottom (Mobile)', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, hidden: ({parent}) => !!parent?.sharePaddingSettings, initialValue: 0}),
      defineField({name: 'paddingInlineStart', title: 'Padding left', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, initialValue: 0}),
      defineField({name: 'paddingInlineStartMobile', title: 'Left (Mobile)', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, hidden: ({parent}) => !!parent?.sharePaddingSettings, initialValue: 0}),
      defineField({name: 'paddingInlineEnd', title: 'Padding right', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, initialValue: 0}),
      defineField({name: 'paddingInlineEndMobile', title: 'Right (Mobile)', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, hidden: ({parent}) => !!parent?.sharePaddingSettings, initialValue: 0}),
  
    ],
    preview: {
      select: {title: 'title'},
      prepare: ({title}) => ({
        title: title || 'Group Block',
        subtitle: 'Group Block',
      }),
    },
  })