import {defineField, defineType} from 'sanity'

export default defineType({
    name: 'textBlock',
    title: 'Text',
    type: 'object',
    fields: [
      defineField({
        name: 'title',
        title: 'Title',
        type: 'string',
      }),
      defineField({
        name: 'text',
        title: 'Text',
        type: 'blockContent',
      }),
      defineField({
        name: 'width',
        title: 'Width',
        type: 'string',
        initialValue: 'fit-content',
        options: {
          layout: 'radio',
          list: [
            {title: 'Fit content', value: 'fit-content'},
            {title: 'Fill (100%)', value: '100%'},
          ],
        },
      }),
      defineField({
        name: 'maxWidth',
        title: 'Max width',
        type: 'string',
        initialValue: 'normal',
        options: {
          list: [
            {title: 'Narrow', value: 'narrow'},
            {title: 'Normal', value: 'normal'},
            {title: 'None', value: 'none'},
          ],
        },
      }),
      defineField({
        name: 'alignment',
        title: 'Alignment',
        type: 'string',
        initialValue: 'left',
        options: {list: ['left', 'center', 'right']},
        hidden: ({parent}) => parent?.width !== '100%',
      }),
      defineField({
        name: 'typePreset',
        title: 'Type preset',
        type: 'string',
        initialValue: 'rte',
        options: {
          list: [
            {title: 'Default (Rich text)', value: 'rte'},
            {title: 'Paragraph', value: 'paragraph'},
            {title: 'Paragraph (Large)', value: 'paragraph_2'},
            {title: 'Paragraph (Extra Large)', value: 'paragraph_3'},
            {title: 'H1', value: 'h1'},
            {title: 'H2', value: 'h2'},
            {title: 'H3', value: 'h3'},
            {title: 'H4', value: 'h4'},
            {title: 'H5', value: 'h5'},
            {title: 'H6', value: 'h6'},
            {title: 'Custom', value: 'custom'},
          ],
        },
      }),
  
      // Custom type settings:
      defineField({
        name: 'font',
        title: 'Font',
        type: 'string',
        options: {
          list: [
            {title: 'Body', value: 'var(--font-body--family)'},
            {title: 'Subheading', value: 'var(--font-subheading--family)'},
            {title: 'Heading', value: 'var(--font-heading--family)'},
            {title: 'Accent', value: 'var(--font-accent--family)'},
          ],
        },
        hidden: ({parent}) => parent?.typePreset !== 'custom',
      }),
      defineField({
        name: 'fontSize',
        title: 'Font size',
        type: 'string',
        initialValue: '1rem',
        options: {
          list: [
            {title: 'Default', value: ''},
            {title: '10px', value: '0.625rem'},
            {title: '12px', value: '0.75rem'},
            {title: '14px', value: '0.875rem'},
            {title: '16px', value: '1rem'},
            {title: '18px', value: '1.125rem'},
            {title: '20px', value: '1.25rem'},
            {title: '22px', value: '1.375rem'},
            {title: '24px', value: '1.5rem'},
            {title: '28px', value: '1.75rem'},
            {title: '32px', value: '2rem'},
            {title: '36px', value: '2.25rem'},
            {title: '40px', value: '2.5rem'},
            {title: '48px', value: '3rem'},
            {title: '60px', value: '3.75rem'},
            {title: '72px', value: '4.5rem'},
            {title: '88px', value: '5.5rem'},
            {title: '120px', value: '7.5rem'},
            {title: '152px', value: '9.5rem'},
            {title: '184px', value: '11.5rem'},
          ],
        },
        hidden: ({parent}) => parent?.typePreset !== 'custom',
      }),
      defineField({
        name: 'fontSizeMobile',
        title: 'Font size (Mobile)',
        type: 'string',
        initialValue: '1rem',
        options: {
          list: [
            {title: 'Default', value: ''},
            {title: '10px', value: '0.625rem'},
            {title: '12px', value: '0.75rem'},
            {title: '14px', value: '0.875rem'},
            {title: '16px', value: '1rem'},
            {title: '18px', value: '1.125rem'},
            {title: '20px', value: '1.25rem'},
            {title: '22px', value: '1.375rem'},
            {title: '24px', value: '1.5rem'},
            {title: '28px', value: '1.75rem'},
            {title: '32px', value: '2rem'},
            {title: '36px', value: '2.25rem'},
            {title: '40px', value: '2.5rem'},
            {title: '48px', value: '3rem'},
            {title: '60px', value: '3.75rem'},
            {title: '72px', value: '4.5rem'},
            {title: '88px', value: '5.5rem'},
            {title: '120px', value: '7.5rem'},
            {title: '152px', value: '9.5rem'},
            {title: '184px', value: '11.5rem'},
          ],
        },
        hidden: ({parent}) => parent?.typePreset !== 'custom',
      }),
      defineField({
        name: 'lineHeight',
        title: 'Line height',
        type: 'string',
        initialValue: 'normal',
        options: {
          list: [
            {title: 'Tight', value: 'tight'},
            {title: 'Normal', value: 'normal'},
            {title: 'Loose', value: 'loose'},
          ],
        },
        hidden: ({parent}) => parent?.typePreset !== 'custom',
      }),
      defineField({
        name: 'letterSpacing',
        title: 'Letter spacing',
        type: 'string',
        initialValue: 'normal',
        options: {
          list: [
            {title: 'Tight', value: 'tight'},
            {title: 'Normal', value: 'normal'},
            {title: 'Loose', value: 'loose'},
          ],
        },
        hidden: ({parent}) => parent?.typePreset !== 'custom',
      }),
      defineField({
        name: 'textTransform',
        title: 'Case',
        type: 'string',
        initialValue: 'none',
        options: {list: [
          {title: 'Default', value: 'none'},
          {title: 'Uppercase', value: 'uppercase'},
        ]},
        hidden: ({parent}) => parent?.typePreset !== 'custom',
      }),
      defineField({
        name: 'textWrap',
        title: 'Wrap',
        type: 'string',
        options: {list: [
          {title: 'Pretty', value: 'pretty'},
          {title: 'Balance', value: 'balance'},
          {title: 'No wrap', value: 'nowrap'},
        ]},
        hidden: ({parent}) => parent?.typePreset !== 'custom',
      }),
  
      
      defineField({
        name: 'color',
        title: 'Color',
        type: 'string',
        initialValue: 'var(--color-foreground)',
        options: {list: [
          {title: 'Text', value: 'var(--color-foreground)'},
          {title: 'Heading', value: 'var(--color-foreground-heading)'},
          {title: 'Link', value: 'var(--color-primary)'},
        ]},
        hidden: ({parent}) => parent?.typePreset === 'rte',
      }),
      defineField({
        name: 'background',
        title: 'Background',
        type: 'boolean',
        initialValue: false,
      }),
      defineField({
        name: 'backgroundColor',
        title: 'Background color',
        type: 'color',
        hidden: ({parent}) => !parent?.background,
      }),
      defineField({
        name: 'cornerRadius',
        title: 'Corner radius',
        type: 'number',
        initialValue: 0,
        hidden: ({parent}) => !parent?.background,
        options: {layout: 'slider', min: 0, max: 50, step: 1},
      }),
      defineField({
        name: 'paddingBlockStart',
        title: 'Padding top',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 0,
      }),
      defineField({
        name: 'paddingBlockEnd',
        title: 'Padding bottom',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 0,
      }),
      defineField({
        name: 'paddingInlineStart',
        title: 'Padding left',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 0,
      }),
      defineField({
        name: 'paddingInlineEnd',
        title: 'Padding right',
        type: 'number',
        options: {layout: 'slider', min: 0, max: 100, step: 1},
        initialValue: 0,
      }),
    ],
    preview: {
      select: { title: 'title'},
      prepare: ({title}) => ({
        title: title || 'Text',
        subtitle: 'Text Block',
      }),
    },
  })