import {defineField, defineType} from 'sanity'

export const textBlock = defineType({
  name: 'textBlock',
  title: 'Text',
  type: 'object',
  fields: [
    defineField({
      name: 'text',
      title: 'Text',
      type: 'blockContent',
    }),
    defineField({
      name: 'width',
      title: 'Width',
      type: 'string',
      initialValue: 'fit-content',
      options: {
        layout: 'radio',
        list: [
          {title: 'Fit content', value: 'fit-content'},
          {title: 'Fill (100%)', value: '100%'},
        ],
      },
    }),
    defineField({
      name: 'maxWidth',
      title: 'Max width',
      type: 'string',
      initialValue: 'normal',
      options: {
        list: [
          {title: 'Narrow', value: 'narrow'},
          {title: 'Normal', value: 'normal'},
          {title: 'None', value: 'none'},
        ],
      },
    }),
    defineField({
      name: 'alignment',
      title: 'Alignment',
      type: 'string',
      initialValue: 'left',
      options: {list: ['left', 'center', 'right']},
      hidden: ({parent}) => parent?.width !== '100%',
    }),
    defineField({
      name: 'typePreset',
      title: 'Type preset',
      type: 'string',
      initialValue: 'rte',
      options: {
        list: [
          {title: 'Default (Rich text)', value: 'rte'},
          {title: 'Paragraph', value: 'paragraph'},
          {title: 'Paragraph (Large)', value: 'paragraph_2'},
          {title: 'Paragraph (Extra Large)', value: 'paragraph_3'},
          {title: 'H1', value: 'h1'},
          {title: 'H2', value: 'h2'},
          {title: 'H3', value: 'h3'},
          {title: 'H4', value: 'h4'},
          {title: 'H5', value: 'h5'},
          {title: 'H6', value: 'h6'},
          {title: 'Custom', value: 'custom'},
        ],
      },
    }),
    defineField({
      name: 'font',
      title: 'Font',
      type: 'string',
      options: {
        list: [
          {title: 'Body', value: 'var(--font-body--family)'},
          {title: 'Subheading', value: 'var(--font-subheading--family)'},
          {title: 'Heading', value: 'var(--font-heading--family)'},
          {title: 'Accent', value: 'var(--font-accent--family)'},
        ],
      },
      hidden: ({parent}) => parent?.typePreset !== 'custom',
    }),
    defineField({
      name: 'fontSize',
      title: 'Font size',
      type: 'string',
      initialValue: '1rem',
      options: {
        list: [
          {title: 'Default', value: ''},
          {title: '10px', value: '0.625rem'},
          {title: '12px', value: '0.75rem'},
          {title: '14px', value: '0.875rem'},
          {title: '16px', value: '1rem'},
          {title: '18px', value: '1.125rem'},
          {title: '20px', value: '1.25rem'},
          {title: '22px', value: '1.375rem'},
          {title: '24px', value: '1.5rem'},
          {title: '28px', value: '1.75rem'},
          {title: '32px', value: '2rem'},
          {title: '36px', value: '2.25rem'},
          {title: '40px', value: '2.5rem'},
          {title: '48px', value: '3rem'},
          {title: '60px', value: '3.75rem'},
          {title: '72px', value: '4.5rem'},
          {title: '88px', value: '5.5rem'},
          {title: '120px', value: '7.5rem'},
          {title: '152px', value: '9.5rem'},
          {title: '184px', value: '11.5rem'},
        ],
      },
      hidden: ({parent}) => parent?.typePreset !== 'custom',
    }),
    defineField({
      name: 'fontSizeMobile',
      title: 'Font size (Mobile)',
      type: 'string',
      initialValue: '1rem',
      options: {
        list: [
          {title: 'Default', value: ''},
          {title: '10px', value: '0.625rem'},
          {title: '12px', value: '0.75rem'},
          {title: '14px', value: '0.875rem'},
          {title: '16px', value: '1rem'},
          {title: '18px', value: '1.125rem'},
          {title: '20px', value: '1.25rem'},
          {title: '22px', value: '1.375rem'},
          {title: '24px', value: '1.5rem'},
          {title: '28px', value: '1.75rem'},
          {title: '32px', value: '2rem'},
          {title: '36px', value: '2.25rem'},
          {title: '40px', value: '2.5rem'},
          {title: '48px', value: '3rem'},
          {title: '60px', value: '3.75rem'},
          {title: '72px', value: '4.5rem'},
          {title: '88px', value: '5.5rem'},
          {title: '120px', value: '7.5rem'},
          {title: '152px', value: '9.5rem'},
          {title: '184px', value: '11.5rem'},
        ],
      },
      hidden: ({parent}) => parent?.typePreset !== 'custom',
    }),
    defineField({
      name: 'lineHeight',
      title: 'Line height',
      type: 'string',
      initialValue: 'normal',
      options: {
        list: [
          {title: 'Tight', value: 'tight'},
          {title: 'Normal', value: 'normal'},
          {title: 'Loose', value: 'loose'},
        ],
      },
      hidden: ({parent}) => parent?.typePreset !== 'custom',
    }),
    defineField({
      name: 'letterSpacing',
      title: 'Letter spacing',
      type: 'string',
      initialValue: 'normal',
      options: {
        list: [
          {title: 'Tight', value: 'tight'},
          {title: 'Normal', value: 'normal'},
          {title: 'Loose', value: 'loose'},
        ],
      },
      hidden: ({parent}) => parent?.typePreset !== 'custom',
    }),
    defineField({
      name: 'textTransform',
      title: 'Case',
      type: 'string',
      initialValue: 'none',
      options: {list: [
        {title: 'Default', value: 'none'},
        {title: 'Uppercase', value: 'uppercase'},
      ]},
      hidden: ({parent}) => parent?.typePreset !== 'custom',
    }),
    defineField({
      name: 'textWrap',
      title: 'Wrap',
      type: 'string',
      options: {list: [
        {title: 'Pretty', value: 'pretty'},
        {title: 'Balance', value: 'balance'},
        {title: 'No wrap', value: 'nowrap'},
      ]},
      hidden: ({parent}) => parent?.typePreset !== 'custom',
    }),
    defineField({
      name: 'color',
      title: 'Color',
      type: 'string',
      initialValue: 'var(--color-foreground)',
      options: {list: [
        {title: 'Text', value: 'var(--color-foreground)'},
        {title: 'Heading', value: 'var(--color-foreground-heading)'},
        {title: 'Link', value: 'var(--color-primary)'},
      ]},
      hidden: ({parent}) => parent?.typePreset === 'rte',
    }),
    defineField({
      name: 'background',
      title: 'Background',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'backgroundColor',
      title: 'Background color',
      type: 'color',
      hidden: ({parent}) => !parent?.background,
    }),
    defineField({
      name: 'cornerRadius',
      title: 'Corner radius',
      type: 'number',
      initialValue: 0,
      hidden: ({parent}) => !parent?.background,
      options: {layout: 'slider', min: 0, max: 50, step: 1},
    }),
    defineField({
      name: 'paddingBlockStart',
      title: 'Padding top',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'paddingBlockEnd',
      title: 'Padding bottom',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'paddingInlineStart',
      title: 'Padding left',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'paddingInlineEnd',
      title: 'Padding right',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
  ],
  preview: {
    select: {text: 'text'},
    prepare: () => ({title: 'Text'}),
  },
})

export const groupBlock = defineType({
  name: 'groupBlock',
  title: 'Group',
  type: 'object',
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string',}),

    defineField({name: 'link', title: 'Link', type: 'url'}),
    defineField({name: 'openInNewTab', title: 'Open in new tab', type: 'boolean', initialValue: false}),
    defineField({name: 'shareLayoutSettings', title: 'Share layout settings across devices', type: 'boolean', initialValue: true}),
    defineField({
      name: 'contentDirection',
      title: 'Content direction',
      type: 'string',
      initialValue: 'column',
      options: {list: [
        {title: 'Vertical', value: 'column'},
        {title: 'Horizontal', value: 'row'},
      ]},
    }),
    defineField({
      name: 'verticalOnMobile',
      title: 'Vertical on mobile',
      type: 'boolean',
      initialValue: true,
      hidden: ({parent}) => parent?.contentDirection !== 'row',
    }),
    defineField({
      name: 'horizontalAlignment',
      title: 'Horizontal alignment',
      type: 'string',
      initialValue: 'flex-start',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({parent}) => parent?.contentDirection !== 'row',
    }),
    defineField({
      name: 'horizontalAlignmentMobile',
      title: 'Horizontal alignment (Mobile)',
      type: 'string',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({parent}) => parent?.contentDirection !== 'row' || !!parent?.shareLayoutSettings,
    }),
    defineField({
      name: 'verticalAlignment',
      title: 'Vertical alignment',
      type: 'string',
      initialValue: 'center',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
      ]},
      hidden: ({parent}) => parent?.contentDirection !== 'row',
    }),
    defineField({
      name: 'verticalAlignmentMobile',
      title: 'Vertical alignment (Mobile)',
      type: 'string',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
      ]},
      hidden: ({parent}) => parent?.contentDirection !== 'row' || !!parent?.shareLayoutSettings,
    }),
    defineField({
      name: 'alignBaseline',
      title: 'Align baseline',
      type: 'boolean',
      initialValue: false,
      hidden: ({parent}) => parent?.verticalAlignment !== 'flex-end',
    }),
    defineField({
      name: 'horizontalAlignmentColumn',
      title: 'Horizontal alignment (column)',
      type: 'string',
      initialValue: 'flex-start',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
      ]},
      hidden: ({parent}) => parent?.contentDirection === 'row',
    }),
    defineField({
      name: 'horizontalAlignmentColumnMobile',
      title: 'Horizontal alignment (column, Mobile)',
      type: 'string',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
      ]},
      hidden: ({parent}) => parent?.contentDirection === 'row' || !!parent?.shareLayoutSettings,
    }),
    defineField({
      name: 'verticalAlignmentColumn',
      title: 'Vertical alignment (column)',
      type: 'string',
      initialValue: 'center',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({parent}) => parent?.contentDirection !== 'column',
    }),
    defineField({
      name: 'verticalAlignmentColumnMobile',
      title: 'Vertical alignment (column, Mobile)',
      type: 'string',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({parent}) => parent?.contentDirection !== 'column' || !!parent?.shareLayoutSettings,
    }),
    defineField({
      name: 'gap',
      title: 'Gap',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 12,
    }),
    defineField({
      name: 'gapMobile',
      title: 'Gap (Mobile)',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      hidden: ({parent}) => !!parent?.shareLayoutSettings,
    }),

    defineField({
      name: 'width',
      title: 'Width',
      type: 'string',
      initialValue: 'fill',
      options: {list: [
        {title: 'Fit content', value: 'fit-content'},
        {title: 'Fill', value: 'fill'},
        {title: 'Custom', value: 'custom'},
      ]},
    }),
    defineField({
      name: 'customWidth',
      title: 'Custom width (%)',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 100,
      hidden: ({parent}) => parent?.width !== 'custom',
    }),
    defineField({
      name: 'widthMobile',
      title: 'Width (Mobile)',
      type: 'string',
      initialValue: 'fill',
      options: {list: [
        {title: 'Fit content', value: 'fit-content'},
        {title: 'Fill', value: 'fill'},
        {title: 'Custom', value: 'custom'},
      ]},
    }),
    defineField({
      name: 'customWidthMobile',
      title: 'Custom width (Mobile, %)',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 100,
      hidden: ({parent}) => parent?.widthMobile !== 'custom',
    }),
    defineField({
      name: 'height',
      title: 'Height',
      type: 'string',
      initialValue: 'fit',
      options: {list: [
        {title: 'Fit content', value: 'fit'},
        {title: 'Fill', value: 'fill'},
        {title: 'Custom', value: 'custom'},
      ]},
    }),
    defineField({
      name: 'customHeight',
      title: 'Custom height (%)',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 100,
      hidden: ({parent}) => parent?.height !== 'custom',
    }),

    defineField({name: 'shareAppearanceSettings', title: 'Share appearance settings across devices', type: 'boolean', initialValue: true}),
    defineField({
      name: 'inheritColorScheme',
      title: 'Inherit color scheme',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'colorScheme',
      title: 'Color scheme',
      type: 'string',
      initialValue: 'scheme-1',
      options: {list: [
        {title: 'Scheme 1', value: 'scheme-1'},
        {title: 'Scheme 2', value: 'scheme-2'},
        {title: 'Scheme 3', value: 'scheme-3'},
        {title: 'Scheme 4', value: 'scheme-4'},
        {title: 'Scheme 5', value: 'scheme-5'},
      ]},
      hidden: ({parent}) => !!parent?.inheritColorScheme,
    }),
    defineField({
      name: 'backgroundMedia',
      title: 'Background media',
      type: 'string',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Image', value: 'image'},
        {title: 'Video', value: 'video'},
      ]},
    }),
    defineField({
      name: 'backgroundMediaMobile',
      title: 'Background media (Mobile)',
      type: 'string',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Image', value: 'image'},
        {title: 'Video', value: 'video'},
      ]},
      hidden: ({parent}) => !!parent?.shareAppearanceSettings,
    }),
    defineField({
      name: 'video',
      title: 'Video',
      type: 'file',
      hidden: ({parent}) => parent?.backgroundMedia !== 'video',
    }),
    defineField({
      name: 'videoPosition',
      title: 'Video position',
      type: 'string',
      initialValue: 'cover',
      options: {list: [
        {title: 'Cover', value: 'cover'},
        {title: 'Contain', value: 'contain'},
      ]},
      hidden: ({parent}) => parent?.backgroundMedia !== 'video',
    }),
    defineField({
      name: 'backgroundImage',
      title: 'Background image',
      type: 'image',
      hidden: ({parent}) => parent?.backgroundMedia !== 'image',
    }),
    defineField({
      name: 'backgroundImagePosition',
      title: 'Image position',
      type: 'string',
      initialValue: 'cover',
      options: {list: [
        {title: 'Cover', value: 'cover'},
        {title: 'Fit', value: 'fit'},
      ]},
      hidden: ({parent}) => parent?.backgroundMedia !== 'image',
    }),

    defineField({
      name: 'border',
      title: 'Borders',
      type: 'string',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Solid', value: 'solid'},
      ]},
    }),
    defineField({
      name: 'borderWidth',
      title: 'Border width (px)',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 10, step: 0.5},
      initialValue: 1,
      hidden: ({parent}) => parent?.border === 'none',
    }),
    defineField({
      name: 'borderOpacity',
      title: 'Border opacity (%)',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 100,
      hidden: ({parent}) => parent?.border === 'none',
    }),
    defineField({
      name: 'borderRadius',
      title: 'Border radius (px)',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'borderRadiusMobile',
      title: 'Border radius (Mobile, px)',
      type: 'number',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
      hidden: ({parent}) => !!parent?.shareAppearanceSettings,
    }),

    defineField({name: 'visibility', title: 'Visibility', type: 'string', initialValue: 'visible-all', options: {list: [
      {title: 'All devices', value: 'visible-all'},
      {title: 'Mobile only', value: 'hidden--desktop'},
      {title: 'Desktop only', value: 'hidden--mobile'},
    ]}}),

    defineField({name: 'toggleOverlay', title: 'Background overlay', type: 'boolean', initialValue: false}),
    defineField({name: 'overlayColor', title: 'Overlay color', type: 'color', hidden: ({parent}) => !parent?.toggleOverlay}),
    defineField({
      name: 'overlayStyle',
      title: 'Overlay style',
      type: 'string',
      initialValue: 'solid',
      options: {list: [
        {title: 'Solid', value: 'solid'},
        {title: 'Gradient', value: 'gradient'},
      ]},
      hidden: ({parent}) => !parent?.toggleOverlay,
    }),
    defineField({
      name: 'gradientDirection',
      title: 'Gradient direction',
      type: 'string',
      initialValue: 'to top',
      options: {list: [
        {title: 'Up', value: 'to top'},
        {title: 'Down', value: 'to bottom'},
      ]},
      hidden: ({parent}) => !parent?.toggleOverlay || parent?.overlayStyle !== 'gradient',
    }),

    defineField({name: 'sharePaddingSettings', title: 'Share padding settings across devices', type: 'boolean', initialValue: true}),
    defineField({name: 'paddingBlockStart', title: 'Padding top', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, initialValue: 0}),
    defineField({name: 'paddingBlockStartMobile', title: 'Top (Mobile)', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, hidden: ({parent}) => !!parent?.sharePaddingSettings, initialValue: 0}),
    defineField({name: 'paddingBlockEnd', title: 'Padding bottom', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, initialValue: 0}),
    defineField({name: 'paddingBlockEndMobile', title: 'Bottom (Mobile)', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, hidden: ({parent}) => !!parent?.sharePaddingSettings, initialValue: 0}),
    defineField({name: 'paddingInlineStart', title: 'Padding left', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, initialValue: 0}),
    defineField({name: 'paddingInlineStartMobile', title: 'Left (Mobile)', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, hidden: ({parent}) => !!parent?.sharePaddingSettings, initialValue: 0}),
    defineField({name: 'paddingInlineEnd', title: 'Padding right', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, initialValue: 0}),
    defineField({name: 'paddingInlineEndMobile', title: 'Right (Mobile)', type: 'number', options: {layout: 'slider', min: 0, max: 100, step: 1}, hidden: ({parent}) => !!parent?.sharePaddingSettings, initialValue: 0}),

    defineField({
      name: 'blocks',
      title: 'Blocks',
      type: 'array',
      of: [{type: 'textBlock'}],
    }),
  ],
  preview: {
    prepare: () => ({title: 'Group'}),
  },
})

export default defineType({
  name: 'section',
  title: 'Section',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content'},
    {name: 'layout', title: 'Layout', default: true},
    {name: 'appearance', title: 'Appearance'},
    {name: 'padding', title: 'Padding'},
  ],
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', group: 'content'}),
    defineField({
      name: 'blocks',
      title: 'Blocks',
      type: 'array',
      group: 'content',
      of: [
        {type: 'groupBlock'},
        {type: 'textBlock'},
      ],
    }),
    defineField({name: 'shareLayoutSettings', title: 'Share layout settings across devices', type: 'boolean', group: 'layout', initialValue: true}),
    defineField({
      name: 'contentDirection',
      title: 'Content direction',
      type: 'string',
      group: 'layout',
      initialValue: 'column',
      options: {list: [
        {title: 'Vertical', value: 'column'},
        {title: 'Horizontal', value: 'row'},
      ]},
    }),
    defineField({
      name: 'verticalOnMobile',
      title: 'Vertical on mobile',
      type: 'boolean',
      group: 'layout',
      initialValue: true,
      hidden: ({document}) => document?.contentDirection !== 'row',
    }),
    defineField({
      name: 'horizontalAlignment',
      title: 'Horizontal alignment',
      type: 'string',
      group: 'layout',
      initialValue: 'flex-start',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'row',
    }),
    defineField({
      name: 'horizontalAlignmentMobile',
      title: 'Horizontal alignment (Mobile)',
      type: 'string',
      group: 'layout',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'row' || !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'verticalAlignment',
      title: 'Vertical alignment',
      type: 'string',
      group: 'layout',
      initialValue: 'center',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'row',
    }),
    defineField({
      name: 'verticalAlignmentMobile',
      title: 'Vertical alignment (Mobile)',
      type: 'string',
      group: 'layout',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'row' || !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'alignBaseline',
      title: 'Align baseline',
      type: 'boolean',
      group: 'layout',
      initialValue: false,
      hidden: ({document}) => document?.verticalAlignment !== 'flex-end',
    }),
    defineField({
      name: 'horizontalAlignmentColumn',
      title: 'Horizontal alignment (column)',
      type: 'string',
      group: 'layout',
      initialValue: 'flex-start',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
      ]},
      hidden: ({document}) => document?.contentDirection === 'row',
    }),
    defineField({
      name: 'horizontalAlignmentColumnMobile',
      title: 'Horizontal alignment (column, Mobile)',
      type: 'string',
      group: 'layout',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
      ]},
      hidden: ({document}) => document?.contentDirection === 'row' || !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'verticalAlignmentColumn',
      title: 'Vertical alignment (column)',
      type: 'string',
      group: 'layout',
      initialValue: 'center',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'column',
    }),
    defineField({
      name: 'verticalAlignmentColumnMobile',
      title: 'Vertical alignment (column, Mobile)',
      type: 'string',
      group: 'layout',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'column' || !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'gap',
      title: 'Gap',
      type: 'number',
      group: 'layout',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 12,
    }),
    defineField({
      name: 'gapMobile',
      title: 'Gap (Mobile)',
      type: 'number',
      group: 'layout',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      hidden: ({document}) => !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'sectionWidth',
      title: 'Section width',
      type: 'string',
      group: 'layout',
      initialValue: 'page-width',
      options: {list: [
        {title: 'Page width', value: 'page-width'},
        {title: 'Full width', value: 'full-width'},
      ]},
    }),
    defineField({
      name: 'sectionHeight',
      title: 'Section height',
      type: 'string',
      group: 'layout',
      initialValue: 'auto',
      options: {list: [
        {title: 'Auto', value: 'auto'},
        {title: 'Small', value: 'small'},
        {title: 'Medium', value: 'medium'},
        {title: 'Large', value: 'large'},
        {title: 'Full screen', value: 'full-screen'},
        {title: 'Custom', value: 'custom'},
      ]},
    }),
    defineField({
      name: 'sectionHeightCustom',
      title: 'Custom height (%)',
      type: 'number',
      group: 'layout',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 50,
      hidden: ({document}) => document?.sectionHeight !== 'custom',
    }),

    defineField({name: 'shareAppearanceSettings', title: 'Share appearance settings across devices', type: 'boolean', group: 'appearance', initialValue: true}),
    defineField({
      name: 'colorScheme',
      title: 'Color scheme',
      type: 'string',
      group: 'appearance',
      initialValue: '',
      options: {list: [
        {title: 'Inherit', value: ''},
        {title: 'Scheme 1', value: 'scheme-1'},
        {title: 'Scheme 2', value: 'scheme-2'},
        {title: 'Scheme 3', value: 'scheme-3'},
        {title: 'Scheme 4', value: 'scheme-4'},
        {title: 'Scheme 5', value: 'scheme-5'},
      ]},
    }),
    defineField({
      name: 'backgroundMedia',
      title: 'Background media',
      type: 'string',
      group: 'appearance',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Image', value: 'image'},
        {title: 'Video', value: 'video'},
      ]},
    }),
    defineField({
      name: 'backgroundMediaMobile',
      title: 'Background media (Mobile)',
      type: 'string',
      group: 'appearance',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Image', value: 'image'},
        {title: 'Video', value: 'video'},
      ]},
      hidden: ({document}) => !!document?.shareAppearanceSettings,
    }),
    defineField({
      name: 'video',
      title: 'Video',
      type: 'file',
      group: 'appearance',
      hidden: ({document}) => document?.backgroundMedia !== 'video',
    }),
    defineField({
      name: 'videoPosition',
      title: 'Video position',
      type: 'string',
      group: 'appearance',
      initialValue: 'cover',
      options: {list: [
        {title: 'Cover', value: 'cover'},
        {title: 'Contain', value: 'contain'},
      ]},
      hidden: ({document}) => document?.backgroundMedia !== 'video',
    }),
    defineField({
      name: 'backgroundImage',
      title: 'Background image',
      type: 'image',
      group: 'appearance',
      hidden: ({document}) => document?.backgroundMedia !== 'image',
    }),
    defineField({
      name: 'backgroundImagePosition',
      title: 'Image position',
      type: 'string',
      group: 'appearance',
      initialValue: 'cover',
      options: {list: [
        {title: 'Cover', value: 'cover'},
        {title: 'Fit', value: 'fit'},
      ]},
      hidden: ({document}) => document?.backgroundMedia !== 'image',
    }),
    defineField({
      name: 'border',
      title: 'Borders',
      type: 'string',
      group: 'appearance',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Solid', value: 'solid'},
      ]},
    }),
    defineField({
      name: 'borderWidth',
      title: 'Border width (px)',
      type: 'number',
      group: 'appearance',
      options: {layout: 'slider', min: 0, max: 10, step: 0.5},
      initialValue: 1,
      hidden: ({document}) => document?.border === 'none',
    }),
    defineField({
      name: 'borderOpacity',
      title: 'Border opacity (%)',
      type: 'number',
      group: 'appearance',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 100,
      hidden: ({document}) => document?.border === 'none',
    }),
    defineField({
      name: 'borderRadius',
      title: 'Border radius (px)',
      type: 'number',
      group: 'appearance',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'borderRadiusMobile',
      title: 'Border radius (Mobile, px)',
      type: 'number',
      group: 'appearance',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
      hidden: ({document}) => !!document?.shareAppearanceSettings,
    }),
    defineField({
      name: 'toggleOverlay',
      title: 'Background overlay',
      type: 'boolean',
      group: 'appearance',
      initialValue: false,
    }),
    defineField({
      name: 'overlayColor',
      title: 'Overlay color',
      type: 'color',
      group: 'appearance',
      hidden: ({document}) => !document?.toggleOverlay,
    }),
    defineField({
      name: 'overlayStyle',
      title: 'Overlay style',
      type: 'string',
      group: 'appearance',
      initialValue: 'solid',
      options: {list: [
        {title: 'Solid', value: 'solid'},
        {title: 'Gradient', value: 'gradient'},
      ]},
      hidden: ({document}) => !document?.toggleOverlay,
    }),
    defineField({
      name: 'gradientDirection',
      title: 'Gradient direction',
      type: 'string',
      group: 'appearance',
      initialValue: 'to top',
      options: {list: [
        {title: 'Up', value: 'to top'},
        {title: 'Down', value: 'to bottom'},
      ]},
      hidden: ({document}) => !document?.toggleOverlay || document?.overlayStyle !== 'gradient',
    }),

    defineField({name: 'sharePaddingSettings', title: 'Share padding settings across devices', type: 'boolean', group: 'padding', initialValue: true}),
    defineField({
      name: 'paddingBlockStart',
      title: 'Padding top',
      type: 'number',
      group: 'padding',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'paddingBlockEnd',
      title: 'Padding bottom',
      type: 'number',
      group: 'padding',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'paddingBlockStartMobile',
      title: 'Padding top (Mobile)',
      type: 'number',
      group: 'padding',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      hidden: ({document}) => !!document?.sharePaddingSettings,
      initialValue: 0,
    }),
    defineField({
      name: 'paddingBlockEndMobile',
      title: 'Padding bottom (Mobile)',
      type: 'number',
      group: 'padding',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      hidden: ({document}) => !!document?.sharePaddingSettings,
      initialValue: 0,
    }),
  ],
  preview: {
    select: {title: 'title'},
    prepare: ({title}) => ({
      title: title || 'Section',
      subtitle: 'Custom Section',
    }),
  },
})


