import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'section',
  title: 'Section',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'layout', title: 'Layout'},
    {name: 'appearance', title: 'Appearance'},
    {name: 'padding', title: 'Padding'},
  ],
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', group: 'content'}),
    defineField({
      name: 'blocks',
      title: 'Blocks',
      type: 'array',
      group: 'content',
      of: [
        {type: 'groupBlock'},
        {type: 'textBlock'},
      ],
    }),
    defineField({name: 'shareLayoutSettings', title: 'Share layout settings across devices', type: 'boolean', group: 'layout', initialValue: true}),
    defineField({
      name: 'contentDirection',
      title: 'Content direction',
      type: 'string',
      group: 'layout',
      initialValue: 'column',
      options: {list: [
        {title: 'Vertical', value: 'column'},
        {title: 'Horizontal', value: 'row'},
      ]},
    }),
    defineField({
      name: 'verticalOnMobile',
      title: 'Vertical on mobile',
      type: 'boolean',
      group: 'layout',
      initialValue: true,
      hidden: ({document}) => document?.contentDirection !== 'row',
    }),
    defineField({
      name: 'horizontalAlignment',
      title: 'Horizontal alignment',
      type: 'string',
      group: 'layout',
      initialValue: 'flex-start',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'row',
    }),
    defineField({
      name: 'horizontalAlignmentMobile',
      title: 'Horizontal alignment (Mobile)',
      type: 'string',
      group: 'layout',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'row' || !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'verticalAlignment',
      title: 'Vertical alignment',
      type: 'string',
      group: 'layout',
      initialValue: 'center',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'row',
    }),
    defineField({
      name: 'verticalAlignmentMobile',
      title: 'Vertical alignment (Mobile)',
      type: 'string',
      group: 'layout',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'row' || !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'alignBaseline',
      title: 'Align baseline',
      type: 'boolean',
      group: 'layout',
      initialValue: false,
      hidden: ({document}) => document?.verticalAlignment !== 'flex-end',
    }),
    defineField({
      name: 'horizontalAlignmentColumn',
      title: 'Horizontal alignment (column)',
      type: 'string',
      group: 'layout',
      initialValue: 'flex-start',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
      ]},
      hidden: ({document}) => document?.contentDirection === 'row',
    }),
    defineField({
      name: 'horizontalAlignmentColumnMobile',
      title: 'Horizontal alignment (column, Mobile)',
      type: 'string',
      group: 'layout',
      options: {list: [
        {title: 'Left', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Right', value: 'flex-end'},
      ]},
      hidden: ({document}) => document?.contentDirection === 'row' || !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'verticalAlignmentColumn',
      title: 'Vertical alignment (column)',
      type: 'string',
      group: 'layout',
      initialValue: 'center',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'column',
    }),
    defineField({
      name: 'verticalAlignmentColumnMobile',
      title: 'Vertical alignment (column, Mobile)',
      type: 'string',
      group: 'layout',
      options: {list: [
        {title: 'Top', value: 'flex-start'},
        {title: 'Center', value: 'center'},
        {title: 'Bottom', value: 'flex-end'},
        {title: 'Space between', value: 'space-between'},
      ]},
      hidden: ({document}) => document?.contentDirection !== 'column' || !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'gap',
      title: 'Gap',
      type: 'number',
      group: 'layout',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 12,
    }),
    defineField({
      name: 'gapMobile',
      title: 'Gap (Mobile)',
      type: 'number',
      group: 'layout',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      hidden: ({document}) => !!document?.shareLayoutSettings,
    }),
    defineField({
      name: 'sectionWidth',
      title: 'Section width',
      type: 'string',
      group: 'layout',
      initialValue: 'page-width',
      options: {list: [
        {title: 'Page width', value: 'page-width'},
        {title: 'Full width', value: 'full-width'},
      ]},
    }),
    defineField({
      name: 'sectionHeight',
      title: 'Section height',
      type: 'string',
      group: 'layout',
      initialValue: 'auto',
      options: {list: [
        {title: 'Auto', value: 'auto'},
        {title: 'Small', value: 'small'},
        {title: 'Medium', value: 'medium'},
        {title: 'Large', value: 'large'},
        {title: 'Full screen', value: 'full-screen'},
        {title: 'Custom', value: 'custom'},
      ]},
    }),
    defineField({
      name: 'sectionHeightCustom',
      title: 'Custom height (%)',
      type: 'number',
      group: 'layout',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 50,
      hidden: ({document}) => document?.sectionHeight !== 'custom',
    }),

    defineField({name: 'shareAppearanceSettings', title: 'Share appearance settings across devices', type: 'boolean', group: 'appearance', initialValue: true}),
    defineField({
      name: 'colorScheme',
      title: 'Color scheme',
      type: 'string',
      group: 'appearance',
      initialValue: '',
      options: {list: [
        {title: 'Inherit', value: ''},
        {title: 'Scheme 1', value: 'scheme-1'},
        {title: 'Scheme 2', value: 'scheme-2'},
        {title: 'Scheme 3', value: 'scheme-3'},
        {title: 'Scheme 4', value: 'scheme-4'},
        {title: 'Scheme 5', value: 'scheme-5'},
      ]},
    }),
    defineField({
      name: 'backgroundMedia',
      title: 'Background media',
      type: 'string',
      group: 'appearance',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Image', value: 'image'},
        {title: 'Video', value: 'video'},
      ]},
    }),
    defineField({
      name: 'backgroundMediaMobile',
      title: 'Background media (Mobile)',
      type: 'string',
      group: 'appearance',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Image', value: 'image'},
        {title: 'Video', value: 'video'},
      ]},
      hidden: ({document}) => !!document?.shareAppearanceSettings,
    }),
    defineField({
      name: 'video',
      title: 'Video',
      type: 'file',
      group: 'appearance',
      hidden: ({document}) => document?.backgroundMedia !== 'video',
    }),
    defineField({
      name: 'videoPosition',
      title: 'Video position',
      type: 'string',
      group: 'appearance',
      initialValue: 'cover',
      options: {list: [
        {title: 'Cover', value: 'cover'},
        {title: 'Contain', value: 'contain'},
      ]},
      hidden: ({document}) => document?.backgroundMedia !== 'video',
    }),
    defineField({
      name: 'backgroundImage',
      title: 'Background image',
      type: 'image',
      group: 'appearance',
      hidden: ({document}) => document?.backgroundMedia !== 'image',
    }),
    defineField({
      name: 'backgroundImagePosition',
      title: 'Image position',
      type: 'string',
      group: 'appearance',
      initialValue: 'cover',
      options: {list: [
        {title: 'Cover', value: 'cover'},
        {title: 'Fit', value: 'fit'},
      ]},
      hidden: ({document}) => document?.backgroundMedia !== 'image',
    }),
    defineField({
      name: 'border',
      title: 'Borders',
      type: 'string',
      group: 'appearance',
      initialValue: 'none',
      options: {list: [
        {title: 'None', value: 'none'},
        {title: 'Solid', value: 'solid'},
      ]},
    }),
    defineField({
      name: 'borderWidth',
      title: 'Border width (px)',
      type: 'number',
      group: 'appearance',
      options: {layout: 'slider', min: 0, max: 10, step: 0.5},
      initialValue: 1,
      hidden: ({document}) => document?.border === 'none',
    }),
    defineField({
      name: 'borderOpacity',
      title: 'Border opacity (%)',
      type: 'number',
      group: 'appearance',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 100,
      hidden: ({document}) => document?.border === 'none',
    }),
    defineField({
      name: 'borderRadius',
      title: 'Border radius (px)',
      type: 'number',
      group: 'appearance',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'borderRadiusMobile',
      title: 'Border radius (Mobile, px)',
      type: 'number',
      group: 'appearance',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
      hidden: ({document}) => !!document?.shareAppearanceSettings,
    }),
    defineField({
      name: 'toggleOverlay',
      title: 'Background overlay',
      type: 'boolean',
      group: 'appearance',
      initialValue: false,
    }),
    defineField({
      name: 'overlayColor',
      title: 'Overlay color',
      type: 'color',
      group: 'appearance',
      hidden: ({document}) => !document?.toggleOverlay,
    }),
    defineField({
      name: 'overlayStyle',
      title: 'Overlay style',
      type: 'string',
      group: 'appearance',
      initialValue: 'solid',
      options: {list: [
        {title: 'Solid', value: 'solid'},
        {title: 'Gradient', value: 'gradient'},
      ]},
      hidden: ({document}) => !document?.toggleOverlay,
    }),
    defineField({
      name: 'gradientDirection',
      title: 'Gradient direction',
      type: 'string',
      group: 'appearance',
      initialValue: 'to top',
      options: {list: [
        {title: 'Up', value: 'to top'},
        {title: 'Down', value: 'to bottom'},
      ]},
      hidden: ({document}) => !document?.toggleOverlay || document?.overlayStyle !== 'gradient',
    }),

    defineField({name: 'sharePaddingSettings', title: 'Share padding settings across devices', type: 'boolean', group: 'padding', initialValue: true}),
    defineField({
      name: 'paddingBlockStart',
      title: 'Padding top',
      type: 'number',
      group: 'padding',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'paddingBlockEnd',
      title: 'Padding bottom',
      type: 'number',
      group: 'padding',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      initialValue: 0,
    }),
    defineField({
      name: 'paddingBlockStartMobile',
      title: 'Padding top (Mobile)',
      type: 'number',
      group: 'padding',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      hidden: ({document}) => !!document?.sharePaddingSettings,
      initialValue: 0,
    }),
    defineField({
      name: 'paddingBlockEndMobile',
      title: 'Padding bottom (Mobile)',
      type: 'number',
      group: 'padding',
      options: {layout: 'slider', min: 0, max: 100, step: 1},
      hidden: ({document}) => !!document?.sharePaddingSettings,
      initialValue: 0,
    }),
  ],
  preview: {
    select: {title: 'title'},
    prepare: ({title}) => ({
      title: title || 'Section',
      subtitle: 'Custom Section',
    }),
  },
})


