import { defineField, defineType } from "sanity";
import { ChartUpwardIcon, CogIcon } from "@sanity/icons";

export default defineType({
	name: "settings",
	title: "Settings",
	type: "document",
	icon: CogIcon,
	groups: [
		{
			name: "main",
			title: "Main Content",
			default: true
		},
		{
			name: "typography",
			title: "Typography",
		}
	],
	fields: [
		defineField({
			name: "meta_title",
			title: "Site Title",
			type: "string",
		}),
		defineField({
			name: "meta_description",
			title: "Site Description",
			type: "string",
			validation: (Rule) => Rule.max(160)
		}),
		defineField({
			name: "site_favicon",
			title: "Site Favicon",
			type: "image"
		}),
		defineField({
			name: "og_image",
			title: "Open Graph Image",
			type: "image"
		}),
		defineField({
			name: "site_scripts",
			description: "Place any sitewide scripts or pixels here",
			title: "Site Scripts / Pixels",
			type: "text",
		}),
		// Typography Settings
		defineField({
			name: "h1_fontSize",
			title: "H1 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 48,
		}),
		defineField({
			name: "h1_fontSizeMobile",
			title: "H1 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 32,
		}),
		defineField({
			name: "h1_lineHeight",
			title: "H1 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.2,
		}),
		defineField({
			name: "h1_lineHeightMobile",
			title: "H1 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.1,
		}),
		defineField({
			name: "h1_letterSpacing",
			title: "H1 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: -0.02,
		}),
		defineField({
			name: "h1_letterSpacingMobile",
			title: "H1 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: -0.01,
		}),
		defineField({
			name: "h1_textTransform",
			title: "H1 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "h2_fontSize",
			title: "H2 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 36,
		}),
		defineField({
			name: "h2_fontSizeMobile",
			title: "H2 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 28,
		}),
		defineField({
			name: "h2_lineHeight",
			title: "H2 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.3,
		}),
		defineField({
			name: "h2_lineHeightMobile",
			title: "H2 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.2,
		}),
		defineField({
			name: "h2_letterSpacing",
			title: "H2 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: -0.01,
		}),
		defineField({
			name: "h2_letterSpacingMobile",
			title: "H2 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h2_textTransform",
			title: "H2 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "h3_fontSize",
			title: "H3 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 28,
		}),
		defineField({
			name: "h3_fontSizeMobile",
			title: "H3 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 24,
		}),
		defineField({
			name: "h3_lineHeight",
			title: "H3 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.3,
		}),
		defineField({
			name: "h3_lineHeightMobile",
			title: "H3 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.2,
		}),
		defineField({
			name: "h3_letterSpacing",
			title: "H3 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h3_letterSpacingMobile",
			title: "H3 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h3_textTransform",
			title: "H3 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "h4_fontSize",
			title: "H4 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 24,
		}),
		defineField({
			name: "h4_fontSizeMobile",
			title: "H4 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 20,
		}),
		defineField({
			name: "h4_lineHeight",
			title: "H4 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.4,
		}),
		defineField({
			name: "h4_lineHeightMobile",
			title: "H4 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.3,
		}),
		defineField({
			name: "h4_letterSpacing",
			title: "H4 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h4_letterSpacingMobile",
			title: "H4 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h4_textTransform",
			title: "H4 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "h5_fontSize",
			title: "H5 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 20,
		}),
		defineField({
			name: "h5_fontSizeMobile",
			title: "H5 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 18,
		}),
		defineField({
			name: "h5_lineHeight",
			title: "H5 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.4,
		}),
		defineField({
			name: "h5_lineHeightMobile",
			title: "H5 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.3,
		}),
		defineField({
			name: "h5_letterSpacing",
			title: "H5 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h5_letterSpacingMobile",
			title: "H5 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h5_textTransform",
			title: "H5 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "h6_fontSize",
			title: "H6 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 18,
		}),
		defineField({
			name: "h6_fontSizeMobile",
			title: "H6 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 16,
		}),
		defineField({
			name: "h6_lineHeight",
			title: "H6 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.4,
		}),
		defineField({
			name: "h6_lineHeightMobile",
			title: "H6 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.3,
		}),
		defineField({
			name: "h6_letterSpacing",
			title: "H6 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h6_letterSpacingMobile",
			title: "H6 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "h6_textTransform",
			title: "H6 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "paragraph_fontSize",
			title: "Paragraph Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 16,
		}),
		defineField({
			name: "paragraph_fontSizeMobile",
			title: "Paragraph Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 14,
		}),
		defineField({
			name: "paragraph_lineHeight",
			title: "Paragraph Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.6,
		}),
		defineField({
			name: "paragraph_lineHeightMobile",
			title: "Paragraph Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.5,
		}),
		defineField({
			name: "paragraph_letterSpacing",
			title: "Paragraph Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "paragraph_letterSpacingMobile",
			title: "Paragraph Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "paragraph_textTransform",
			title: "Paragraph Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "paragraph_2_fontSize",
			title: "Paragraph 2 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 18,
		}),
		defineField({
			name: "paragraph_2_fontSizeMobile",
			title: "Paragraph 2 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 16,
		}),
		defineField({
			name: "paragraph_2_lineHeight",
			title: "Paragraph 2 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.6,
		}),
		defineField({
			name: "paragraph_2_lineHeightMobile",
			title: "Paragraph 2 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.5,
		}),
		defineField({
			name: "paragraph_2_letterSpacing",
			title: "Paragraph 2 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "paragraph_2_letterSpacingMobile",
			title: "Paragraph 2 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "paragraph_2_textTransform",
			title: "Paragraph 2 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "paragraph_3_fontSize",
			title: "Paragraph 3 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 20,
		}),
		defineField({
			name: "paragraph_3_fontSizeMobile",
			title: "Paragraph 3 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 18,
		}),
		defineField({
			name: "paragraph_3_lineHeight",
			title: "Paragraph 3 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.6,
		}),
		defineField({
			name: "paragraph_3_lineHeightMobile",
			title: "Paragraph 3 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.5,
		}),
		defineField({
			name: "paragraph_3_letterSpacing",
			title: "Paragraph 3 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "paragraph_3_letterSpacingMobile",
			title: "Paragraph 3 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0,
		}),
		defineField({
			name: "paragraph_3_textTransform",
			title: "Paragraph 3 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "none",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "eyebrow_fontSize",
			title: "Eyebrow Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 14,
		}),
		defineField({
			name: "eyebrow_fontSizeMobile",
			title: "Eyebrow Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 12,
		}),
		defineField({
			name: "eyebrow_lineHeight",
			title: "Eyebrow Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.4,
		}),
		defineField({
			name: "eyebrow_lineHeightMobile",
			title: "Eyebrow Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.3,
		}),
		defineField({
			name: "eyebrow_letterSpacing",
			title: "Eyebrow Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0.1,
		}),
		defineField({
			name: "eyebrow_letterSpacingMobile",
			title: "Eyebrow Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0.05,
		}),
		defineField({
			name: "eyebrow_textTransform",
			title: "Eyebrow Text Transform",
			type: "string",
			group: "typography",
			initialValue: "uppercase",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
		defineField({
			name: "eyebrow_2_fontSize",
			title: "Eyebrow 2 Font Size (px)",
			type: "number",
			group: "typography",
			initialValue: 16,
		}),
		defineField({
			name: "eyebrow_2_fontSizeMobile",
			title: "Eyebrow 2 Font Size Mobile (px)",
			type: "number",
			group: "typography",
			initialValue: 14,
		}),
		defineField({
			name: "eyebrow_2_lineHeight",
			title: "Eyebrow 2 Line Height",
			type: "number",
			group: "typography",
			initialValue: 1.4,
		}),
		defineField({
			name: "eyebrow_2_lineHeightMobile",
			title: "Eyebrow 2 Line Height Mobile",
			type: "number",
			group: "typography",
			initialValue: 1.3,
		}),
		defineField({
			name: "eyebrow_2_letterSpacing",
			title: "Eyebrow 2 Letter Spacing",
			type: "number",
			group: "typography",
			initialValue: 0.05,
		}),
		defineField({
			name: "eyebrow_2_letterSpacingMobile",
			title: "Eyebrow 2 Letter Spacing Mobile",
			type: "number",
			group: "typography",
			initialValue: 0.02,
		}),
		defineField({
			name: "eyebrow_2_textTransform",
			title: "Eyebrow 2 Text Transform",
			type: "string",
			group: "typography",
			initialValue: "uppercase",
			options: {
				list: [
					{title: "None", value: "none"},
					{title: "Uppercase", value: "uppercase"},
					{title: "Lowercase", value: "lowercase"},
					{title: "Capitalize", value: "capitalize"},
				],
			},
		}),
	]
});